["directories"]
input_path = "C:/Users/eserkai/OneDrive - Ericsson/Documents/Programming/Python/Training/recharge-file-handling/sample_data"
log_path = "C:/Users/eserkai/OneDrive - Ericsson/Documents/Programming/Python/Training/recharge-file-handling/logs"
csv_path = "C:/Users/eserkai/OneDrive - Ericsson/Documents/Programming/Python/Training/recharge-file-handling/csv"

["database"]
db_host = "localhost"
db_name = "postgres" #default database to establish connection
db_user = "postgres"
db_password = "training"

["operation"]
send_to_database = "YES"